export const routerMap = new Map([
  ['/home', '../views//SandBoxView/Home/HomeView'],
  ['/user-manage/add', '../views/SandBoxView/UserManage/UserAdd.tsx'],
  ['/user-manage/delete', '../views/SandBoxView/UserManage/UserDelete.tsx'],
  ['/user-manage/update', '../views//SandBoxView/UserManage/UserUpdate.tsx'],
  ['/user-manage/list', '../views//SandBoxView/UserManage/UserView'],
  ['/right-manage/role/list', '../views//SandBoxView/RightManage/RoleView'],
  ['/right-manage/right/list', '../views//SandBoxView/RightManage/RightView'],
  ['/right-manage/role/update', '../views/SandBoxView/RightManage/RoleUpdate.tsx'],
  ['/right-manage/role/delete', '../views/SandBoxView/RightManage/RoleDelete.tsx'],
  ['/right-manage/right/update', '../views//SandBoxView/RightManage/RightUpdate.tsx'],
  ['/right-manage/right/delete', '../views//SandBoxView/RightManage/RightDelete.tsx'],
  ['/news-manage/list', '../views/SandBoxView/NewsManage/NewsView.tsx'],
  ['/news-manage/add', '../views//SandBoxView/NewsManage/NewsAdd.tsx'],
  ['/news-manage/update/:id', '../views/SandBoxView/NewsManage/NewsUpdate.tsx'],
  ['/news-manage/preview/:id', '../views/SandBoxView/NewsManage/NewsPreview.tsx'],
  ['/news-manage/draft', '../views/SandBoxView/NewsManage/NewsDraft.tsx'],
  ['/news-manage/category', '../views/SandBoxView/NewsManage/NewsCategory.tsx'],
  ['/audit-manage/audit', '../views/SandBoxView/AuditManage/AuditD.tsx'],
  ['/audit-manage/list', '../views/SandBoxView/AuditManage/AuditView.tsx'],
  ['/publish-manage/unpublished', '../views/SandBoxView/PublishManage/AuditUnPub.tsx'],
  ['/publish-manage/published', '../views/SandBoxView/PublishManage/AuditPub.tsx'],
  ['/publish-manage/sunset', '../views/SandBoxView/PublishManage/AuditSunSet.tsx']
])
